version: "3.9"

services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "jobcrawler"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres_data:
    driver: local