management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'healthcheck', 'prometheus' ]
      base-path: '/admin'
      path-mapping:
        prometheus: '/metrics'

spring:
  application.name: job-crawler
  datasource:
    url: '${DB_URL}'
    driverClassName: org.postgresql.Driver
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase_changelog.xml

springdoc:
  api-docs:
    path: /apidoc
  swagger-ui:
    path: /swagger-ui/index.html


